HugoGresse/OpenPlanner

- .github/workflows/firebase-hosting-merge.yml
- .github/workflows/firebase-hosting-pull-request.yml
- firestore.rules
- index.html
- src/App.tsx
- src/auth/RequireLogin.tsx
- src/auth/authReducer.ts
- src/components/CCLink.tsx
- src/components/FirestoreQueryLoaderAndErrorDisplay.tsx
- src/events/EventsLayout.tsx
- src/events/EventsListItem.tsx
- src/events/EventsScreen.tsx
- src/services/firebase.ts
- src/services/hooks/useEvents.ts
- src/types.ts
- src/utils/MD5.ts
This PR setup roots for future dev: 
- load data from Firestore using React Query Firebase https://react-query-firebase.invertase.dev
> Display events

- src/events/actions/addNewEvent.ts
- src/events/page/EventLayout.tsx
- src/events/page/EventRouter.tsx
- src/events/page/EventScreenMenuItems.tsx
- src/events/page/schedule/NoDatesSessionsPicker.tsx
- src/events/page/schedule/components/SessionCard.tsx
- src/events/page/sessions/EventSession.tsx
- src/events/page/sessions/EventSessionItem.tsx
- src/events/page/sessions/EventSessions.tsx
- src/services/hooks/useSession.ts
- src/utils/diffDays.ts
- src/utils/timeFormats.ts
- list sessions + raw session data display in edit
- fix overflow in Session pick in schedule
- add separator when creating event
- fix seconds when adjusting session duration
> List sessions + fix some stuff

- src/events/actions/updateWebsiteActions/updateWebsiteTriggerWebhooksAction.ts
- src/events/page/EventRouter.tsx
- src/events/page/sessions/EventSession.tsx
- src/events/page/sessions/EventSessionForm.tsx
- src/events/page/sessions/EventSessions.tsx
- src/events/page/sessions/NewSession.tsx
- src/events/page/speakers/EventSpeakers.tsx
> Implement new session

- src/events/actions/addNewEvent.ts
- src/events/actions/conferenceHallUtils/addNewEventDateUtils.ts
- src/events/page/EventRouter.tsx
- src/events/page/schedule/components/SessionCardContent.tsx
- src/events/page/sessions/EventSession.tsx
- src/events/page/sessions/EventSessionForm.tsx
- src/events/page/sessions/list/EventSessions.tsx
- src/events/page/sessions/list/FilterCategory.tsx
- src/events/page/sessions/list/FilterFormat.tsx
- src/events/page/speakers/EventSpeaker.tsx
- src/events/page/speakers/EventSpeakerForm.tsx
- src/events/page/speakers/EventSpeakerItem.tsx
- src/events/page/speakers/EventSpeakers.tsx
- src/services/hooks/useSessions.ts
- src/types.ts
- src/utils/isBackSameDomain.ts
- src/utils/navigateBackOrFallbackTo.ts
- live update in schedule
- fix undefined categories from CH 
- redirect to schedule if event dates & tracks are set 
- improve new date when importing from CH, closing #18 
- add counts to Format & Categories in filters
- add link from Session's speaker to speaker page
- display sessions from Speakers list
> Small improvements

- src/App.tsx
- src/components/SuspenseLoader.tsx
- src/events/page/EventRouter.tsx
- tsconfig.json
> Use suspense everywhere!

- functions/src/api/file/files.ts
- functions/src/api/index.ts
- functions/src/api/sponsors/sponsors.ts
- functions/src/api/swagger.ts
- add better desc in swagger
- add better to support to running the API out of Firebase Functions
> Improve swagger

- functions/package.json
- functions/src/api/file/files.ts
- functions/src/api/index.ts
- functions/src/api/sponsors/sponsors.ts
- add a new param to the sponsor API POST to reupload the provided logoUrl to internal storage
> Add reupload params to sponsor API

- src/events/page/faq/EventFaq.tsx
- src/events/page/faq/FaqCategoryItem.tsx
- src/events/page/faq/FaqCategoryItemContent.tsx
- src/events/page/faq/faqLink.ts
- src/hooks/useSearchParams.ts
- src/public/PublicApp.tsx
- src/public/faq/FaqQuestion.tsx
- src/public/faq/PublicFaqCategory.tsx
- fix colors in light/dark mode 
- fix responsive design
- highlight question from url on app open 
- improve faq loader design
- backoffice:
- add edit category name button
- add delete category button
- add FAQ link
> Improvement faq (colors, responsive, loader, and highlight question from url)

- README.md
- functions/src/api/sponsors/sponsors.ts
- reUploadAssets were not working on the API due to bad programmation
> API: Fix reUploadAssets not working

- README.md
- src/App.tsx
- src/auth/ForgotPasswordScreen.tsx
- src/auth/LoginForm.tsx
- src/auth/authReducer.ts
> Implement reset password

- functions/.env.example
- functions/src/api/file/files.ts
- functions/src/api/file/parseMultipartFiles.ts
- functions/src/api/other/checkFileTypes.ts
- src/components/sidepanel/SidePanelImageUpload.tsx
- src/components/sidepanel/SidePanelImageUploadForm.tsx
- src/utils/images/resizeImage.ts
> Manage svg upload through UI & API 

- src/events/page/schedule/components/SessionCardContent.tsx
- src/events/page/schedule/components/TemplateCardContent.tsx
- src/events/page/schedule/components/TemplateDialog.tsx
- src/events/page/settings/EventSettingsFormatCategoriesGrid.tsx
- add totals in formats/categories grids 
- add start/end time on schedule events
> Add totals in formats/categories grids & start/end time on schedule events

- src/events/page/EventRouter.tsx
- src/events/page/speakers/EventSpeaker.tsx
- src/services/hooks/firestoreQueryHook.ts
- fix next/prev speaker not working
- display current index near next/prev speaker count 
- remove EventSpeakers for lazy loading stuff
> Fix next/prev speaker not working and display speaker count

- src/events/actions/conferenceHallUtils/mapFromConferenceHallToOpenPlanner.ts
> Fix possible error with null/undefined ID when importing from ConferenceHall on sessions & speaker DisplayName 

- src/components/sidepanel/SidePanelImageUpload.tsx
> Fix max resolution image upload issue

- src/components/form/VideoTextFieldElement.tsx
- src/components/sidepanel/SidePanelVideoPreview.tsx
- src/events/actions/addNewEvent.ts
- src/events/actions/sessions/generation/generateSessionTeasingContent.ts
- src/events/actions/sessions/generation/generateSessionTeasingTexts.ts
- src/events/actions/sessions/generation/useSessionsGenerationGeneric.ts
- src/events/new/NewEventDialog.tsx
- src/events/page/sessions/EventSessionForm.tsx
- src/events/page/sessions/components/GenerateSessionsTextContentDialog.tsx
- src/events/page/sessions/components/GenerateSessionsVideoDialog.tsx
- src/events/page/sessions/components/SessionAISettings.tsx
- src/events/page/sessions/components/ShortVidSettings.tsx
- src/events/page/sessions/list/EventSessions.tsx
- src/services/openai.ts
- src/types.ts
- add generation of text and media on session edition form
- add AI settings (prompt + model + temperature)
- explain ShortVid expected input format
> Add text and video generation on single session + AI settings 

- functions/src/api/routes/sessions/sessions.ts
- src/events/actions/sessions/generation/generateShortVid.ts
- src/events/actions/sessions/generation/shortVidAPI.ts
- src/events/page/sessions/components/GenerateSessionsVideoDialog.tsx
- src/events/page/sessions/components/ShortVidSettings.tsx
- src/services/hooks/firestoreQueryHook.ts
- src/types.ts
- remove console.error in firestoreQueryHook
- Improve shortvid error management & add new params to pick the endpoint
> Shortvid new server + API change for shortvid 

- src/components/form/ImageTextFieldElement.tsx
- src/components/sidepanel/SidePanelVideoPreview.tsx
- src/events/page/sessions/EventSessionForm.tsx
> Improve file download for image in sessions (file name + download button directly on the input)

- src/components/form/ImageTextFieldElement.tsx
- src/components/sidepanel/SidePanelVideoPreview.tsx
- src/events/page/sessions/EventSessionForm.tsx
- src/events/page/sponsors/components/SponsorCategoryItem.tsx
- src/utils/Zip.ts
- src/utils/images/downloadImages.ts
- add new button to download a sponsor category images as one zip
- add confirm dialog when deleting a sponsor category
> Download all sponsors logo as one zip

- src/events/page/speakers/EventSpeakers.tsx
- src/events/page/team/EventTeam.tsx
- src/utils/Zip.ts
- add export on Team page to download all images as zip
- fix zip sometimes corrupted due to accent
> Team download + fix zip sometimes corrupted

- functions/src/api/index.ts
> Remove cache on API

- functions/src/api/dao/eventDao.ts
> Fix:API await when creating formats and categories

- src/events/page/team/components/MemberForm.tsx
- src/types.ts
> feat(team): add optional bio field in team members.

- src/events/page/team/EventMember.tsx
- src/events/page/team/components/MemberForm.tsx
- src/events/page/team/hooks/useTeamDragAndDrop.ts
- fix free minor issues related to teams and member behaviors
> Fixes tean drag issues 

- src/events/page/settings/EventSettingsFormatCategoriesGrid.tsx
> Fix category and formats counts when no category and no formats

- src/events/actions/sessions/getTemplate.ts
- src/events/page/schedule/components/TemplateDialog.tsx
- src/events/page/schedule/components/TemplateImportDialog.tsx
You can now import a template from a prior event to the current event, with day, format and categories matching
> Add import templates button

- functions/src/api/routes/sessionsSpeakers/sessionsSpeakers.ts
- add phone and email field to speaker API
> Add phone and email to API

- functions/src/api/routes/faq/faq.ts
- src/events/page/faq/FaqCategoryItem.tsx
- src/events/page/faq/FaqCategoryItemContent.tsx
- src/public/faq/PublicFaqCategory.tsx
- src/public/publicTypes.ts
- src/types.ts
- new FAQ option to display the FAQ as a single unified page without needing to open or close each question
> Add FAQ unified option

- src/events/page/speakers/EventSpeaker.tsx
- src/events/page/speakers/EventSpeakerForm.tsx
- src/events/page/speakers/EventSpeakers.tsx
- src/events/page/speakers/components/SpeakerSessions.tsx
- src/services/hooks/firestoreMutationHooks.ts
- src/services/hooks/useSpeakerSessions.ts
- new filter on speaker list for no session speaker, closing #119 
- display session list in speaker detail 
- fix error still displayed on save if next save actually work
> Feat: Session list in speakers and speaker filter for no sesisons 

- README.md
- src/components/sidepanel/ImageCropDialog.tsx
- src/components/sidepanel/SidePanelImageUpload.tsx
- src/components/sidepanel/SidePanelImageUploadForm.tsx
- src/utils/imageCropUtils.ts
- src/utils/images/imageCrop/cropJpegImage.ts
- src/utils/images/imageCrop/cropPngImage.ts
- src/utils/images/imageCrop/cropSvgImage.ts
- src/utils/images/imageCrop/detectImageType.ts
- src/utils/images/loadImageWithCORS.ts
- add crop editor for png/jpg and svg. SVG cropping use the viewBox so this SVG stay vectorized! 
Close #175
> Feat: add drop function

- src/events/actions/getFaq.ts
- src/events/page/faq/EventFaq.tsx
- src/events/page/faq/components/FaqCategoryImportDialog.tsx
- add FAQ Improt from another event
Close #187
> Add FAQ import from another event

- src/events/page/faq/FaqCategoryItem.tsx
- src/events/page/faq/FaqCategoryItemContent.tsx
- src/events/page/faq/FaqItem.tsx
- add faq question reordering using the drag handle
Close #173
> Add reordering to FAQ questions

- functions/src/api/routes/deploy/updateWebsiteActions/triggerWebhooks.ts
- src/events/page/layouts/EventDrawerContent.tsx
- src/events/page/settings/components/EventStaticApiFilePaths.tsx
- src/events/page/settings/components/WebhooksFields.tsx
- src/events/page/speakers/NewSpeaker.tsx
- src/events/page/speakers/components/SpeakerSessions.tsx
- src/types.ts
- move the infos on the static API up  #158 
- recommend the user when adding a new speaker to add his email, closing #132 
- save webhooks last trigger date, display it and also display the last event updated at on the update website button
> Feat: email recommendation for new speaker + date on deploy and webhooks 

- functions/src/api/routes/deploy/updateWebsiteActions/generateStaticJson.ts
- src/events/page/sessions/components/GenerateSessionsVideoDialog.tsx
- src/events/page/settings/components/WebhooksFields.tsx
- src/events/page/sponsors/jobposts/JobPosts.tsx
- src/public/jobs/PublicEventJobAdd.tsx
- add filter to generate image/video only to the missing sessions
- add event name, logo and markdown mention to job form
- add delete button on job posts
- add approved jobs to JSONs
> Add filter for session media gen, add job delete button, add event name and logo to job post form and add jobs to JSONs 

- .cursor/rules/backend-structure.mdc
- .cursor/rules/code-organization.mdc
- .cursor/rules/events-sessions.mdc
- .cursor/rules/project-overview.mdc
- .cursor/rules/ui-components.mdc
- src/events/page/sessions/list/EventSessions.tsx
- src/events/page/sessions/list/components/BatchEditDialog.tsx
- src/events/page/sessions/list/hooks/useSessionsBatchEdit.ts
- add session batch edit for a few fields 
- add slightly modified cursor rules
- minor ux change on session not annouced filter
> Session batch edit + cursor rules 

- firestore.indexes.json
- firestore.rules
- src/events/admin/AdminScreen.tsx
- src/services/hooks/useEventStats.ts
- add number of speakers and session in OpenPlanner super admin pannel
> - add number of speakers and session in OpenPlanner super admin pannel

- src/public/jobs/PublicEventJobAdd.tsx
stays displayed 10s before being gone
> Clarrify job post success message

- src/utils/Zip.ts
- src/utils/images/loadAndConvertSvgToPng.ts
> Prevent undefined file name when zipping stuff

- functions/src/api/routes/deploy/getDeployFiles.ts
- functions/src/api/routes/deploy/updateWebsiteActions/generateStaticJson.ts
- functions/src/api/routes/deploy/updateWebsiteActions/getFilesNames.ts
- functions/src/api/routes/deploy/updateWebsiteActions/jsonTypes.ts
- functions/src/api/routes/event/eventRoutes.ts
- functions/src/api/routes/event/exportSchedulePdf.ts
- functions/src/api/routes/event/getPdfMetadata.ts
- functions/src/types.ts
- src/components/PdfScheduleSection.tsx
- src/context/EventFilesContext.tsx
- src/events/page/api/Api.tsx
- src/events/page/settings/components/EventStaticApiFilePaths.tsx
- src/hooks/usePdfGeneration.ts
- src/types.ts
> Add PDF update button + timezone in JSON

- functions/src/api/dao/eventDao.ts
- src/components/sidepanel/SidePanelImageUpload.tsx
- src/components/sidepanel/SidePanelImageUploadForm.tsx
- src/events/new/NewEventDialog.tsx
- src/events/page/schedule/EventSchedule.tsx
- src/events/page/speakers/EventSpeakers.tsx
- src/events/page/speakers/actions/exportSpeakersAction.ts
- src/events/page/sponsors/EventSponsors.tsx
- src/utils/images/getImageInfo.ts
- add speakers csv export, close #217 
- fix sponsors event counts, close #207 
- add image size and type in the side panel, close #215 
- ask for event dates on event creation + aufoFocus, close #216 
- fix copy schedule button, close #208
> Lot of fixes and small improvements
